# Brain AI Framework Configuration
# This configuration file contains all parameters for the neuroimaging AI framework

# Project paths
paths:
  data_root: './data'
  raw_data: './data/raw'
  processed_data: './data/processed'
  clinical_data: './data/clinical'
  models_dir: './models'
  logs_dir: './logs'
  output_dir: './results'

# Data configuration
data:
  raw_dir: './data/raw'
  processed_dir: './data/processed'
  clinical_dir: './data/clinical'
  train_val_test_split: [0.7, 0.15, 0.15]
  image_size: [128, 128, 128]
  spacing: [1.5, 1.5, 1.5]  # mm
  intensity_normalization: 'min_max'  # Options: 'min_max', 'z_score', 'percentile'

  # Data augmentation parameters
  augmentation:
    enable: true
    rotation_range: 15  # degrees
    translation_range: 0.1  # fraction
    scale_range: [0.9, 1.1]
    flip_probability: 0.5
    intensity_shift: 0.1
    intensity_scale: 0.1

# Model configuration
model:
  segmentation:
    type: 'UNet'  # Options: 'UNet', 'DynUNet', 'SegResNet'
    dimensions: 3
    in_channels: 1
    out_channels: 5  # Background + GM + WM + CSF + Abnormality
    features: [32, 64, 128, 256, 320]
    dropout: 0.2
    normalization: 'instance'  # Options: 'batch', 'instance'
    activation: 'relu'
    pretrained_weights: null

  anomaly_detection:
    enable: true
    type: 'UNetWithAttentionGate'  # Options: 'UNetWithAttentionGate', 'AutoEncoder', 'VAE'
    features: [32, 64, 128, 256]
    attention_levels: [1, 2, 3]
    threshold: 0.5  # Anomaly detection threshold

# Training configuration
training:
  optimizer: 'Adam'  # Options: 'Adam', 'SGD', 'AdamW'
  learning_rate: 0.001
  weight_decay: 1e-5
  scheduler: 'CosineAnnealingLR'  # Options: 'CosineAnnealingLR', 'ReduceLROnPlateau', 'StepLR'
  batch_size: 4
  num_epochs: 200
  early_stopping:
    enable: true
    patience: 20
    min_delta: 0.001

  # Loss functions
  loss:
    segmentation: 'DiceCELoss'  # Options: 'DiceLoss', 'DiceCELoss', 'FocalLoss'
    anomaly: 'MSELoss'  # Options: 'MSELoss', 'BCELoss'
    lambda_seg: 1.0
    lambda_anomaly: 0.5

  # Validation
  validation:
    interval: 5  # Validate every N epochs
    metrics: ['dice', 'hausdorff', 'precision', 'recall']
    best_metric: 'dice'
    save_best_only: true

# Inference configuration
inference:
  batch_size: 1
  sliding_window: true
  roi_size: [128, 128, 128]
  overlap: 0.5
  sw_batch_size: 4
  post_process:
    enable: true
    threshold: 0.5
    min_volume: 100  # mm³

# Statistical analysis
analysis:
  significance_level: 0.05
  multiple_comparison_correction: 'fdr_bh'  # Options: 'bonferroni', 'fdr_bh'
  correlation_method: 'pearson'  # Options: 'pearson', 'spearman'
  perform_ttest: true
  perform_anova: true
  cohort_analysis:
    enable: true
    groups: ['CN', 'MCI', 'AD']

  # Visualization
  visualization:
    colormap: 'viridis'
    overlay_alpha: 0.4
    create_heatmaps: true
    create_volume_plots: true
    create_cortical_maps: true

# Web application
webapp:
  host: '0.0.0.0'
  port: 5000
  debug: false
  upload_folder: './webapp/uploads'
  allowed_extensions: ['nii', 'nii.gz']
  max_content_length: 104857600  # 100 MB
  session_secret: 'brain-ai-secret-key'

# System
system:
  seed: 42
  num_workers: 4
  pin_memory: true
  cudnn_benchmark: true
  amp: true  # Automatic mixed precision
  wandb:
    enable: false
    project: 'brain-ai'
    entity: 'user'
    tags: ['brain-segmentation', 'anomaly-detection', 'neuroimaging']

# Clinical data files mapping
clinical_data:
  subject_info: 'ADNI_T1.csv'
  cdr: 'CDR.csv'
  mmse: 'MMSE.csv'
  gdscale: 'GDSCALE.csv'
  adas_adni1: 'ADAS_ADNI1.csv'
  neurobat: 'NEUROBAT.csv'
  demographics: 'PTDEMOG.csv'
  adas_adnigo23: 'ADAS_ADNIGO23.csv'